---
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
      gitlab_runner_activate: False
      gitlab_runner_reregister:
        unregister_all: True
        register_all: True
        gitlab_url: https://git.example.com
        registration_token: '49045009-df28-459e-8c1e-13b31b8f7763'
        runners:
          - tags:
              - shell
            executor: shell
            limit: 1
          - tags:
            - docker
            executor: docker
            docker_image: ruby:2.1
            env:
              SECRET_NUMBER: 42
          - tags:
            - dnd
            executor: docker
            docker_image: docker:stable
            docker_privileged: yes
            docker_volumes:
              - /certs/client
              - /cache
            env:
              SECRET_NUMBER: 44
