---
- name: add the gitlab-runner user to other groups
  become: yes
  become_user: root
  user:
    name: '{{ gitlab_runner_runas }}'
    append: yes
    groups: '{{ gitlab_runner_addl_groups | default([]) }}'

- name: mkdir config and env directories
  become: yes
  become_user: root
  with_items:
    - d: '{{ gitlab_runner_config_dir }}'
      m: '0600'
  file:
    state: directory
    path: '{{ item.d }}'
    mode: '{{ item.m }}'

- name: templatize environment...
  become: yes
  become_user: root
  notify: gitlab_runner_service_restart
  with_items:
    - t: gitlab-runner.env.j2
      d: '{{ gitlab_runner_config_dir }}'
      f: '{{ gitlab_runner_env_file }}'
      m: '0644'
  template:
    src: '{{ item.t }}'
    dest: '{{ item.d }}/{{ item.f }}'
    mode: '{{ item.m }}'

- name: establish global configs in config.toml
  become: yes
  become_user: root
  notify: gitlab_runner_service_restart
  with_items:
    - regex: '^concurrent'
      line: 'concurrent = {{ gitlab_runner_concurrent_runners_per_host | default(1) }}'
    - regex: '^check_interval'
      line: 'check_interval = {{ gitlab_runner_check_gitlab_new_builds_interval | default(0) }}'
  lineinfile:
    path: '{{ gitlab_runner_config_dir }}/{{ gitlab_runner_config_file }}'
    create: yes
    mode: '0600'
    regex: '{{ item.regex }}'
    line: '{{ item.line }}'
