---
- name: Templatize /etc/{conf.d,init.d}/gitlab-runner
  become: true
  become_user: root
  notify:
    - Gitlab_runner_service_restart
  with_items:
    - d: /etc/conf.d
      f: gitlab-runner
      t: gitlab-runner-confd
      m: '644'
    - d: /etc/init.d
      f: gitlab-runner
      t: gitlab-runner-initd
      m: '644'
  ansible.builtin.template:
    src: '{{ item.t }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    mode: '{{ item.m }}'
