---
- name: templatize the re-registration script
  become: yes
  become_user: root
  template:
    src: gitlab-runner-reregister.sh.j2
    dest: '{{ gitlab_runner_reregister_sh }}'
    mode: 0700
  register: gitlab_runner_reregistration_templated
- name: re-registering the runners
  become: yes
  become_user: root
  when: gitlab_runner_activate and gitlab_runner_reregistration_templated.changed
  command: '{{ gitlab_runner_reregister_sh }}'
  notify: gitlab_runner_service_restart
