---
- name: Install gitlab-runner systemd service
  become: true
  become_user: root
  notify:
    - Gitlab_runner_daemon_reload
    - Gitlab_runner_service_restart
  with_items:
    - d: /etc/systemd/system
      f: gitlab-runner.service
      m: '644'
  ansible.builtin.template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    mode: '{{ item.m }}'
