---
# handlers file for gitlab_runner
- name: gitlab_runner_daemon_reload
  become: yes
  become_user: root
  when: gitlab_runner_activate
  systemd:
    daemon_reload: yes
- name: gitlab_runner_service_restart
  become: yes
  become_user: root
  when: gitlab_runner_activate
  service:
    name: gitlab-runner
    state: restarted
