---
# handlers file for gitlab_runner
- name: Gitlab_runner_daemon_reload
  become: true
  become_user: root
  when: gitlab_runner_activate
  ansible.builtin.systemd:
    daemon_reload: true
- name: Gitlab_runner_service_restart
  become: true
  become_user: root
  when: gitlab_runner_activate
  ansible.builtin.service:
    name: gitlab-runner
    state: restarted
